[auth.email.template.recovery]
subject = "Recuperação de Senha - IAFÉ Finanças"
content_path = "supabase/templates/recovery.html"

[auth.email.template.invite]
subject = "Você foi convidado para o IAFÉ Finanças"
content_path = "supabase/templates/invite.html"

[auth.email.template.confirmation]
subject = "Confirme seu e-mail no IAFÉ Finanças"
content_path = "supabase/templates/confirmation.html"
