UPDATE transactions t SET category = m.slug
FROM (VALUES
  ('Supermercado', 'supermercado'),
  ('Restaurante', 'restaurante'),
  ('Lanchonete / Fast Food', 'lanchonete'),
  ('Padaria', 'padaria'),
  ('Delivery / iFood', 'delivery'),
  ('Açougue', 'acougue'),
  ('Feira / Hortifruti', 'feira'),
  ('Bebidas', 'bebidas'),
  ('Aluguel', 'aluguel'),
  ('Condomínio', 'condominio'),
  ('IPTU', 'iptu'),
  ('Energia Elétrica', 'energia_eletrica'),
  ('Água e Esgoto', 'agua_esgoto'),
  ('Gás', 'gas'),
  ('Internet', 'internet'),
  ('TV por Assinatura', 'tv_assinatura'),
  ('Manutenção da Casa', 'manutencao_casa'),
  ('Seguro Residencial', 'seguro_residencial'),
  ('Combustível', 'combustivel'),
  ('Estacionamento', 'estacionamento'),
  ('Pedágio', 'pedagio'),
  ('Uber / 99 / Táxi', 'uber_99_taxi'),
  ('Ônibus / Metrô', 'transporte_publico'),
  ('Seguro do Veículo', 'seguro_veiculo'),
  ('IPVA', 'ipva'),
  ('Manutenção do Veículo', 'manutencao_veiculo'),
  ('Roupas', 'roupas'),
  ('Calçados', 'calcados'),
  ('Acessórios', 'acessorios_vestuario'),
  ('Plano de Saúde', 'plano_saude'),
  ('Farmácia / Medicamentos', 'farmacia'),
  ('Consulta Médica', 'consulta_medica'),
  ('Dentista', 'dentista'),
  ('Exames / Laboratório', 'exames_laboratorio'),
  ('Terapia / Psicólogo', 'terapia_psicologo'),
  ('Academia / Esporte', 'academia_esporte'),
  ('Escola / Faculdade', 'escola_faculdade'),
  ('Curso Online', 'curso_online'),
  ('Material Escolar', 'material_escolar'),
  ('Livros', 'livros'),
  ('Idiomas', 'idiomas'),
  ('Treinamentos', 'treinamentos'),
  ('Cinema / Teatro', 'cinema_teatro'),
  ('Streaming (Netflix, etc.)', 'streaming'),
  ('Jogos / Games', 'jogos_games'),
  ('Viagens', 'viagens'),
  ('Hospedagem', 'hospedagem'),
  ('Passeios / Parques', 'passeios_parques'),
  ('Shows / Eventos', 'shows_eventos'),
  ('Hobbies', 'hobbies'),
  ('Escola dos Filhos', 'escola_filhos'),
  ('Material dos Filhos', 'material_filhos'),
  ('Brinquedos', 'brinquedos'),
  ('Babá / Creche', 'baba_creche'),
  ('Mesada', 'mesada'),
  ('Ração / Pet Shop', 'racao_petshop'),
  ('Veterinário', 'veterinario'),
  ('Banho e Tosa', 'banho_tosa'),
  ('Acessórios Pet', 'acessorios_pet'),
  ('Material de Escritório', 'material_escritorio'),
  ('Coworking', 'coworking'),
  ('Ferramentas Profissionais', 'ferramentas_profissionais'),
  ('Uniforme / Vestimenta Profissional', 'uniforme_profissional'),
  ('Celular / Telefone', 'celular_telefone'),
  ('Assinaturas Digitais', 'assinaturas_digitais'),
  ('Software / Apps', 'software_apps'),
  ('Equipamentos', 'equipamentos_tech'),
  ('Manutenção de Eletrônicos', 'manutencao_eletronicos'),
  ('Tarifa Bancária', 'tarifa_bancaria'),
  ('Pagamento de Fatura', 'pagamento_fatura'),
  ('Anuidade de Cartão', 'anuidade_cartao'),
  ('Empréstimo', 'emprestimo'),
  ('Financiamento', 'financiamento'),
  ('Consórcio', 'consorcio'),
  ('Investimentos', 'investimentos'),
  ('Previdência Privada', 'previdencia_privada'),
  ('Seguros (Vida, etc.)', 'seguros_vida'),
  ('Presentes', 'presentes'),
  ('Cosméticos / Beleza', 'cosmeticos_beleza'),
  ('Salão / Barbearia', 'salao_barbearia'),
  ('Perfumaria', 'perfumaria'),
  ('Eletrônicos', 'eletronicos_pessoais'),
  ('Decoração', 'decoracao'),
  ('Imposto de Renda', 'imposto_renda'),
  ('INSS', 'inss'),
  ('Taxas Governamentais', 'taxas_governamentais'),
  ('Multas', 'multas'),
  ('Cartório / Documentos', 'cartorio_documentos'),
  ('Doações', 'doacoes'),
  ('Dízimo / Oferta', 'dizimo_oferta'),
  ('Contribuição Sindical', 'contribuicao_sindical'),
  ('Spotify / Música', 'musica_streaming'),
  ('Clube de Assinatura', 'clube_assinatura'),
  ('Jornal / Revista', 'jornal_revista'),
  ('Armazenamento em Nuvem', 'armazenamento_nuvem'),
  ('VPN / Segurança Digital', 'vpn_seguranca'),
  ('Despesas Médicas Emergenciais', 'emergencia_medica'),
  ('Mudança', 'mudanca'),
  ('Frete / Correios', 'frete_correios'),
  ('Serviços (Encanador, Eletricista)', 'servicos_gerais'),
  ('Outros', 'outros'),
  ('Salário', 'salario'),
  ('Freelance / Autônomo', 'freelance'),
  ('Vendas', 'vendas'),
  ('Aluguel Recebido', 'aluguel_recebido'),
  ('Rendimento de Investimentos', 'investimentos_rendimento'),
  ('Bônus / 13° Salário', 'bonus'),
  ('Pensão Recebida', 'pensao_recebida'),
  ('Comissão', 'comissao'),
  ('Reembolso', 'reembolso'),
  ('Presente / Doação Recebida', 'presente_recebido'),
  ('Serviço Prestado', 'servico_prestado'),
  ('Outras Receitas', 'outros_receita'),
  ('Transferência entre Contas', 'transferencia')
) AS m(label, slug)
WHERE trim(t.category) = m.label AND t.category IS DISTINCT FROM m.slug;

UPDATE budgets b SET category = m.slug
FROM (VALUES
  ('Supermercado', 'supermercado'),
  ('Restaurante', 'restaurante'),
  ('Lanchonete / Fast Food', 'lanchonete'),
  ('Padaria', 'padaria'),
  ('Delivery / iFood', 'delivery'),
  ('Açougue', 'acougue'),
  ('Feira / Hortifruti', 'feira'),
  ('Bebidas', 'bebidas'),
  ('Aluguel', 'aluguel'),
  ('Condomínio', 'condominio'),
  ('IPTU', 'iptu'),
  ('Energia Elétrica', 'energia_eletrica'),
  ('Água e Esgoto', 'agua_esgoto'),
  ('Gás', 'gas'),
  ('Internet', 'internet'),
  ('TV por Assinatura', 'tv_assinatura'),
  ('Manutenção da Casa', 'manutencao_casa'),
  ('Seguro Residencial', 'seguro_residencial'),
  ('Combustível', 'combustivel'),
  ('Estacionamento', 'estacionamento'),
  ('Pedágio', 'pedagio'),
  ('Uber / 99 / Táxi', 'uber_99_taxi'),
  ('Ônibus / Metrô', 'transporte_publico'),
  ('Seguro do Veículo', 'seguro_veiculo'),
  ('IPVA', 'ipva'),
  ('Manutenção do Veículo', 'manutencao_veiculo'),
  ('Roupas', 'roupas'),
  ('Calçados', 'calcados'),
  ('Acessórios', 'acessorios_vestuario'),
  ('Plano de Saúde', 'plano_saude'),
  ('Farmácia / Medicamentos', 'farmacia'),
  ('Consulta Médica', 'consulta_medica'),
  ('Dentista', 'dentista'),
  ('Exames / Laboratório', 'exames_laboratorio'),
  ('Terapia / Psicólogo', 'terapia_psicologo'),
  ('Academia / Esporte', 'academia_esporte'),
  ('Escola / Faculdade', 'escola_faculdade'),
  ('Curso Online', 'curso_online'),
  ('Material Escolar', 'material_escolar'),
  ('Livros', 'livros'),
  ('Idiomas', 'idiomas'),
  ('Treinamentos', 'treinamentos'),
  ('Cinema / Teatro', 'cinema_teatro'),
  ('Streaming (Netflix, etc.)', 'streaming'),
  ('Jogos / Games', 'jogos_games'),
  ('Viagens', 'viagens'),
  ('Hospedagem', 'hospedagem'),
  ('Passeios / Parques', 'passeios_parques'),
  ('Shows / Eventos', 'shows_eventos'),
  ('Hobbies', 'hobbies'),
  ('Escola dos Filhos', 'escola_filhos'),
  ('Material dos Filhos', 'material_filhos'),
  ('Brinquedos', 'brinquedos'),
  ('Babá / Creche', 'baba_creche'),
  ('Mesada', 'mesada'),
  ('Ração / Pet Shop', 'racao_petshop'),
  ('Veterinário', 'veterinario'),
  ('Banho e Tosa', 'banho_tosa'),
  ('Acessórios Pet', 'acessorios_pet'),
  ('Material de Escritório', 'material_escritorio'),
  ('Coworking', 'coworking'),
  ('Ferramentas Profissionais', 'ferramentas_profissionais'),
  ('Uniforme / Vestimenta Profissional', 'uniforme_profissional'),
  ('Celular / Telefone', 'celular_telefone'),
  ('Assinaturas Digitais', 'assinaturas_digitais'),
  ('Software / Apps', 'software_apps'),
  ('Equipamentos', 'equipamentos_tech'),
  ('Manutenção de Eletrônicos', 'manutencao_eletronicos'),
  ('Tarifa Bancária', 'tarifa_bancaria'),
  ('Pagamento de Fatura', 'pagamento_fatura'),
  ('Anuidade de Cartão', 'anuidade_cartao'),
  ('Empréstimo', 'emprestimo'),
  ('Financiamento', 'financiamento'),
  ('Consórcio', 'consorcio'),
  ('Investimentos', 'investimentos'),
  ('Previdência Privada', 'previdencia_privada'),
  ('Seguros (Vida, etc.)', 'seguros_vida'),
  ('Presentes', 'presentes'),
  ('Cosméticos / Beleza', 'cosmeticos_beleza'),
  ('Salão / Barbearia', 'salao_barbearia'),
  ('Perfumaria', 'perfumaria'),
  ('Eletrônicos', 'eletronicos_pessoais'),
  ('Decoração', 'decoracao'),
  ('Imposto de Renda', 'imposto_renda'),
  ('INSS', 'inss'),
  ('Taxas Governamentais', 'taxas_governamentais'),
  ('Multas', 'multas'),
  ('Cartório / Documentos', 'cartorio_documentos'),
  ('Doações', 'doacoes'),
  ('Dízimo / Oferta', 'dizimo_oferta'),
  ('Contribuição Sindical', 'contribuicao_sindical'),
  ('Spotify / Música', 'musica_streaming'),
  ('Clube de Assinatura', 'clube_assinatura'),
  ('Jornal / Revista', 'jornal_revista'),
  ('Armazenamento em Nuvem', 'armazenamento_nuvem'),
  ('VPN / Segurança Digital', 'vpn_seguranca'),
  ('Despesas Médicas Emergenciais', 'emergencia_medica'),
  ('Mudança', 'mudanca'),
  ('Frete / Correios', 'frete_correios'),
  ('Serviços (Encanador, Eletricista)', 'servicos_gerais'),
  ('Outros', 'outros'),
  ('Salário', 'salario'),
  ('Freelance / Autônomo', 'freelance'),
  ('Vendas', 'vendas'),
  ('Aluguel Recebido', 'aluguel_recebido'),
  ('Rendimento de Investimentos', 'investimentos_rendimento'),
  ('Bônus / 13° Salário', 'bonus'),
  ('Pensão Recebida', 'pensao_recebida'),
  ('Comissão', 'comissao'),
  ('Reembolso', 'reembolso'),
  ('Presente / Doação Recebida', 'presente_recebido'),
  ('Serviço Prestado', 'servico_prestado'),
  ('Outras Receitas', 'outros_receita'),
  ('Transferência entre Contas', 'transferencia')
) AS m(label, slug)
WHERE trim(b.category) = m.label AND b.category IS DISTINCT FROM m.slug;
